[Version]
Class=IEXPRESS
SEDVersion=3.0

[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles

[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\Tyler\OneDrive\DOCUME~1\NEWPRO~1\SCHOOL~1\dist\Plink.exe
FriendlyName=Plink
AppLaunched=cmd.exe /c LaunchSchoolPlanner.cmd
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="LaunchSchoolPlanner.cmd"
FILE1="index.html"
FILE2="styles.css"
FILE3="app.js"
FILE4="plink.png"
FILE5="plink-user.js"
FILE6="plink-update.js"
FILE7="manifest.json"
FILE8="service-worker.js"
FILE9="README.md"
FILE10="MOBILE_TESTING.md"

[SourceFiles]
SourceFiles0=C:\Users\Tyler\OneDrive\DOCUME~1\NEWPRO~1\SCHOOL~1\

[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
%FILE3%=
%FILE4%=
%FILE5%=
%FILE6%=
%FILE7%=
%FILE8%=
%FILE9%=
%FILE10%=
